options(prompt="R>", scipen=100, digits=4)

library(readxl)
concerns=read_excel("festivaldata-full.xlsx", sheet="specsafety")
concerns$Sex = factor(concerns$Sex)
concerns$Experience = ordered(concerns$Experience)
concerns$Experiencen = ordered(concerns$Experiencen)
concerns$SexOrient = factor(concerns$SexOrient)

sink(file = "3a-results-glm anova-safety concerns-full.txt", append=FALSE)
cat("Physical******************************")
cat(sep="\n")
Physical.glm = glm(Physical ~ Sex + Experience + SexOrient, 
                   family= binomial, data = concerns)
car::Anova(Physical.glm)
cat(sep="\n")

model.matrix(Physical.glm)

cat("CrowdViolence******************************")
cat(sep="\n")
CrowdViolence.glm = glm(CrowdViolence ~ Sex + Experience + SexOrient, 
                        family= binomial, data = concerns)
car::Anova(CrowdViolence.glm)
cat(sep="\n")

cat("Sexual******************************")
cat(sep="\n")
Sexual.glm = glm(Sexual ~ Sex + Experience + SexOrient, 
                 family= binomial, data = concerns)
cat(sep="\n")
car::Anova(Sexual.glm)
cat(sep="\n")

cat("Terrorism******************************")
cat(sep="\n")
Terrorism.glm = glm(Terrorism ~ Sex + Experience + SexOrient, 
                    family= binomial, data = concerns)
car::Anova(Terrorism.glm)
cat(sep="\n")

cat("Police******************************")
cat(sep="\n")
Police.glm = glm(Police ~ Sex + Experience + SexOrient, 
                    family= binomial, data = concerns)
car::Anova(Police.glm)
cat(sep="\n")

cat("Uwanted Security******************************")
cat(sep="\n")
UnwantedSecurity.glm = glm(UnwantedSecurity ~ Sex + Experience + SexOrient, 
                    family= binomial, data = concerns)
car::Anova(UnwantedSecurity.glm)
cat(sep="\n")
sink()

#Check model fit
library(performance)
library(see)
binned_residuals(Physical.glm)
binned_residuals(CrowdViolence.glm)
binned_residuals(Sexual.glm)
binned_residuals(Terrorism.glm)
binned_residuals(Police.glm)
binned_residuals(UnwantedSecurity.glm)

library(broom)
sink(file = "3b-results-glm summary-safety concerns-full.txt", append=FALSE)
tidy(Physical.glm)
tidy(CrowdViolence.glm)
tidy(Sexual.glm)
tidy(Terrorism.glm)
tidy(Police.glm)
tidy(UnwantedSecurity.glm)

confint(Physical.glm)
confint(CrowdViolence.glm)
confint(Sexual.glm)
confint(Terrorism.glm)
confint(Police.glm)
confint(UnwantedSecurity.glm)
sink()

sink(file = "3c-results-glm weighted means-safety concerns-full.txt", append=FALSE)
cat("Police******************************")
cat(sep="\n")
cat("Weighted Means")
cat(sep="\n")
tapply(concerns$Police, concerns$Experience, weighted.mean)
cat(sep="\n")
tapply(concerns$Police, concerns$Sex, weighted.mean)
cat(sep="\n")
tapply(concerns$Police, concerns$SexOrient, weighted.mean)
cat(sep="\n")

cat("Unwanted Security******************************")
cat(sep="\n")
cat("Weighted Means")
cat(sep="\n")
tapply(concerns$UnwantedSecurity, concerns$Experience, weighted.mean)
cat(sep="\n")
tapply(concerns$UnwantedSecurity, concerns$Sex, weighted.mean)
cat(sep="\n")
tapply(concerns$UnwantedSecurity, concerns$SexOrient, weighted.mean)
cat(sep="\n")

cat("Sexual******************************")
cat(sep="\n")
cat("Weighted Means")
cat(sep="\n")
tapply(concerns$Sexual, concerns$Experience, weighted.mean)
cat(sep="\n")
tapply(concerns$Sexual, concerns$Sex, weighted.mean)
cat(sep="\n")
tapply(concerns$Sexual, concerns$SexOrient, weighted.mean)
cat(sep="\n")

cat("Terrorism******************************")
cat(sep="\n")
cat("Weighted Means")
cat(sep="\n")
tapply(concerns$Terrorism, concerns$Experience, weighted.mean)
cat(sep="\n")
tapply(concerns$Terrorism, concerns$Sex, weighted.mean)
cat(sep="\n")
tapply(concerns$Terrorism, concerns$SexOrient, weighted.mean)
cat(sep="\n")

cat("CrowdViolence******************************")
cat(sep="\n")
cat("Weighted Means")
cat(sep="\n")
tapply(concerns$CrowdViolence, concerns$Experience, weighted.mean)
cat(sep="\n")
tapply(concerns$CrowdViolence, concerns$Sex, weighted.mean)
cat(sep="\n")
tapply(concerns$CrowdViolence, concerns$SexOrient, weighted.mean)
cat(sep="\n")
sink()