options(prompt="R>", scipen=100, digits=4)

library(readxl)
measures=read_excel("festivaldata-full.xlsx", sheet="measures")
measures$Sex = factor(measures$Sex)
measures$Experience = ordered(measures$Experience)
measures$Experiencen = ordered(measures$Experiencen)
measures$SexOrient = factor(measures$SexOrient)

sink("3a-results-glm anova-safety measures-full.txt", append = FALSE)
cat("Location******************************")
cat(sep="\n")
Location.glm = glm(Location ~ Sex + Experience + SexOrient, 
                 family = binomial, data = measures)
car::Anova(Location.glm)
cat(sep="\n")
cat("EthosVibe******************************")
cat(sep="\n")
EthosVibe.glm = glm(EthosVibe ~ Sex + Experience + SexOrient, 
                 family = binomial, data = measures)
car::Anova(EthosVibe.glm)
cat(sep="\n")
cat("Police******************************")
cat(sep="\n")
Police.glm = glm(Police ~ Sex + Experience + SexOrient, 
                 family = binomial, data = measures)
car::Anova(Police.glm)
cat(sep="\n")
cat("Surveillance******************************")
cat(sep="\n")
Surveillance.glm = glm(Surveillance ~ Sex + Experience + SexOrient, 
           family = binomial, data = measures)
car::Anova(Surveillance.glm)
cat(sep="\n")
cat("Private Security******************************")
cat(sep="\n")
PvtSecurity.glm = glm(PvtSecurity ~ Sex + Experience + SexOrient, 
                    family = binomial, data = measures)
car::Anova(PvtSecurity.glm)
cat(sep="\n")
cat("Citizen Security******************************")
cat(sep="\n")
CitSecurity.glm = glm(CitSecurity ~ Sex + Experience + SexOrient, 
                      family = binomial, data = measures)
car::Anova(CitSecurity.glm)
cat(sep="\n")
cat("Friends******************************")
cat(sep="\n")
Friends.glm = glm(Friends ~ Sex + Experience + SexOrient, 
               family = binomial, data = measures)
car::Anova(Friends.glm)
cat("Health Tents******************************")
cat(sep="\n")
HealthTents.glm = glm(HealthTents ~ Sex + Experience + SexOrient, 
                  family = binomial, data = measures)
car::Anova(HealthTents.glm)
sink()

#Check model fit
library(performance)
library(see)
binned_residuals(Location.glm)
binned_residuals(EthosVibe.glm)
binned_residuals(Police.glm)
binned_residuals(Surveillance.glm)
binned_residuals(PvtSecurity.glm)
binned_residuals(CitSecurity.glm)
binned_residuals(Friends.glm)
binned_residuals(HealthTents.glm)

library(broom)
sink("3b-results-glm summary-safety measures-full.txt", append = FALSE)
tidy(Location.glm)
tidy(EthosVibe.glm)
tidy(Police.glm)
tidy(Surveillance.glm)
tidy(PvtSecurity.glm)
tidy(CitSecurity.glm)
tidy(Friends.glm)
tidy(HealthTents.glm)

confint(Location.glm)
confint(EthosVibe.glm)
confint(Police.glm)
confint(Surveillance.glm)
confint(PvtSecurity.glm)
confint(CitSecurity.glm)
confint(Friends.glm)
confint(HealthTents.glm)
sink()

sink("3c-results-glm weighted means-safety measures-full.txt", append = FALSE)
cat("Location******************************")
cat(sep="\n")
cat("Weighted Means")
cat(sep="\n")
tapply(measures$Location, measures$Experience, weighted.mean)
cat(sep="\n")
tapply(measures$Location, measures$Sex, weighted.mean)
cat(sep="\n")
tapply(measures$Location, measures$SexOrient, weighted.mean)
cat(sep="\n")
cat("EthosVibe******************************")
cat(sep="\n")
cat("Weighted Means")
cat(sep="\n")
tapply(measures$EthosVibe, measures$Experience, weighted.mean)
cat(sep="\n")
tapply(measures$EthosVibe, measures$Sex, weighted.mean)
cat(sep="\n")
tapply(measures$EthosVibe, measures$SexOrient, weighted.mean)
cat(sep="\n")
cat("Police******************************")
cat(sep="\n")
cat("Weighted Means")
cat(sep="\n")
tapply(measures$Police, measures$Experience, weighted.mean)
cat(sep="\n")
tapply(measures$Police, measures$Sex, weighted.mean)
cat(sep="\n")
tapply(measures$Police, measures$SexOrient, weighted.mean)
cat(sep="\n")
cat("Surveillance******************************")
cat(sep="\n")
cat("Weighted Means")
cat(sep="\n")
tapply(measures$Surveillance, measures$Experience, weighted.mean)
cat(sep="\n")
tapply(measures$Surveillance, measures$Sex, weighted.mean)
cat(sep="\n")
tapply(measures$Surveillance, measures$SexOrient, weighted.mean)
cat(sep="\n")
cat("Private Security******************************")
cat(sep="\n")
cat("Weighted Means")
cat(sep="\n")
tapply(measures$PvtSecurity, measures$Experience, weighted.mean)
cat(sep="\n")
tapply(measures$PvtSecurity, measures$Sex, weighted.mean)
cat(sep="\n")
tapply(measures$PvtSecurity, measures$SexOrient, weighted.mean)
cat(sep="\n")
cat("Citizen Security******************************")
cat(sep="\n")
cat("Weighted Means")
cat(sep="\n")
tapply(measures$CitSecurity, measures$Experience, weighted.mean)
cat(sep="\n")
tapply(measures$CitSecurity, measures$Sex, weighted.mean)
cat(sep="\n")
tapply(measures$CitSecurity, measures$SexOrient, weighted.mean)
cat(sep="\n")
cat("Friends******************************")
cat(sep="\n")
cat("Weighted Means")
cat(sep="\n")
tapply(measures$Friends, measures$Experience, weighted.mean)
cat(sep="\n")
tapply(measures$Friends, measures$Sex, weighted.mean)
cat(sep="\n")
tapply(measures$Friends, measures$SexOrient, weighted.mean)
cat(sep="\n")
cat("Health Tents******************************")
cat(sep="\n")
cat("Weighted Means")
cat(sep="\n")
tapply(measures$HealthTents, measures$Experience, weighted.mean)
cat(sep="\n")
tapply(measures$HealthTents, measures$Sex, weighted.mean)
cat(sep="\n")
tapply(measures$HealthTents, measures$SexOrient, weighted.mean)
cat(sep="\n")
sink()