options(prompt="R>", scipen=100, digits=4)

library(readxl)
feelings=read_excel("festivaldata-full.xlsx", sheet="feelings")
feelings$Sex = factor(feelings$Sex)
feelings$Experience = ordered(feelings$Experience)
feelings$Experiencen = ordered(feelings$Experiencen)
feelings$SexOrient = factor(feelings$SexOrient)

sink(file = "4a-results-glm anova-feelings-full.txt", append = FALSE)
cat("Safe******************************")
cat(sep="\n")
Safe.glm = glm(Safe ~ Sex + Experience + SexOrient, 
               family = binomial, data = feelings)
car::Anova(Safe.glm)
cat(sep="\n")

cat("Watched******************************")
cat(sep="\n")
Watched.glm = glm(Watched ~ Sex + Experience + SexOrient, 
                  family = binomial, data = feelings)
car::Anova(Watched.glm)
cat(sep="\n")

cat("Indifferent******************************")
cat(sep="\n")
Indifferent.glm = glm(Indifferent ~ Sex + Experience + SexOrient, 
                      family = binomial, data = feelings)
car::Anova(Indifferent.glm)
cat(sep="\n")

cat("Anxious******************************")
cat(sep="\n")
Anxious.glm = glm(Anxious ~ Sex + Experience + SexOrient, 
                  family = binomial, data = feelings)
car::Anova(Anxious.glm)
cat(sep="\n")

cat("At Risk******************************")
cat(sep="\n")
AtRisk.glm = glm(AtRisk ~ Sex + Experience + SexOrient, 
                 family = binomial, data = feelings)
car::Anova(AtRisk.glm)
cat(sep="\n")

cat("Changes Vibe******************************")
cat(sep="\n")
ChangesVibe.glm = glm(ChangesVibe ~ Sex + Experience + SexOrient, 
                      family = binomial, data = feelings)
car::Anova(ChangesVibe.glm)
cat(sep="\n")
sink()

#Check model fit
library(performance)
library(see)
binned_residuals(Safe.glm)
binned_residuals(Indifferent.glm)
binned_residuals(ChangesVibe.glm)
binned_residuals(Watched.glm)
binned_residuals(Anxious.glm)
binned_residuals(AtRisk.glm)

library(broom)
sink(file = "4b-results-glm summary-feelings-full.txt", append = FALSE)
tidy(Safe.glm)
tidy(Indifferent.glm)
tidy(ChangesVibe.glm)
tidy(Watched.glm)
tidy(Anxious.glm)
tidy(AtRisk.glm)

confint(Safe.glm)
confint(Indifferent.glm)
confint(ChangesVibe.glm)
confint(Watched.glm)
confint(Anxious.glm)
confint(AtRisk.glm)
sink()

sink(file = "4c-results-glm weighted means-feelings-full.txt", append = FALSE)
cat("Safe******************************")
cat(sep="\n")
cat("Weighted Means")
cat(sep="\n")
tapply(feelings$Safe, feelings$Experience, weighted.mean)
cat(sep="\n")
tapply(feelings$Safe, feelings$Sex, weighted.mean)
cat(sep="\n")
tapply(feelings$Safe, feelings$SexOrient, weighted.mean)
cat(sep="\n")

cat("Indifferent******************************")
cat(sep="\n")
cat("Weighted Means")
cat(sep="\n")
tapply(feelings$Indifferent, feelings$Experience, weighted.mean)
cat(sep="\n")
tapply(feelings$Indifferent, feelings$Sex, weighted.mean)
cat(sep="\n")
tapply(feelings$Indifferent, feelings$SexOrient, weighted.mean)
cat(sep="\n")

cat("ChangesVibe******************************")
cat(sep="\n")
cat("Weighted Means")
cat(sep="\n")
tapply(feelings$ChangesVibe, feelings$Experience, weighted.mean)
cat(sep="\n")
tapply(feelings$ChangesVibe, feelings$Sex, weighted.mean)
cat(sep="\n")
tapply(feelings$ChangesVibe, feelings$SexOrient, weighted.mean)
cat(sep="\n")

cat("Watched******************************")
cat(sep="\n")
cat("Weighted Means")
cat(sep="\n")
tapply(feelings$Watched, feelings$Experience, weighted.mean)
cat(sep="\n")
tapply(feelings$Watched, feelings$Sex, weighted.mean)
cat(sep="\n")
tapply(feelings$Watched, feelings$SexOrient, weighted.mean)
cat(sep="\n")

cat("Anxious******************************")
cat(sep="\n")
cat("Weighted Means")
cat(sep="\n")
tapply(feelings$Anxious, feelings$Experience, weighted.mean)
cat(sep="\n")
tapply(feelings$Anxious, feelings$Sex, weighted.mean)
cat(sep="\n")
tapply(feelings$Anxious, feelings$SexOrient, weighted.mean)
cat(sep="\n")

cat("At Risk******************************")
cat(sep="\n")
cat("Weighted Means")
cat(sep="\n")
tapply(feelings$AtRisk, feelings$Experience, weighted.mean)
cat(sep="\n")
tapply(feelings$AtRisk, feelings$Sex, weighted.mean)
cat(sep="\n")
tapply(feelings$AtRisk, feelings$SexOrient, weighted.mean)
cat(sep="\n")
sink()
